
MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 75

AbcSize:
    Max: 50

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
<<<<<<< HEAD
  Enabled: false

Style/Documentation:
  Enabled: false
=======
    Enabled: false
>>>>>>> update repo
